In [1]:
from benchmarks import benchmark, train, test, sample_sub, sort_ads
from models import VeryNaiveBayes, HomeMadeNaiveBayes
from utils import logger
import numpy as np
import pandas as pd

model = VeryNaiveBayes()
hnb = HomeMadeNaiveBayes()

2016-10-22 23:37:57,001 - utils - INFO - ================START=================

In [4]:
events = pd.read_csv('../../data/raw/events.csv')

/usr/local/lib/python2.7/dist-packages/IPython/core/interactiveshell.py:2717: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [5]:
events

,display_id,uuid,document_id,timestamp,platform,geo_location
0,1,cb8c55702adb93,379743,61,3,US>SC>519
1,2,79a85fa78311b9,1794259,81,2,US>CA>807
2,3,822932ce3d8757,1179111,182,2,US>MI>505
3,4,85281d0a49f7ac,1777797,234,2,US>WV>564
4,5,8d0daef4bf5b56,252458,338,2,SG>00
5,6,7765b4faae4ad4,1773517,395,3,US>OH>510
6,7,2cc3f6457d16da,1149661,602,2,US>MT>762
7,8,166fc654d73c98,1330329,638,2,US>PA>566
8,9,9dddccf70f6067,1772126,667,1,US>FL>528
9,10,b09a0e92aa4d17,157455,693,1,US
10,11,602e210c5831e5,1773230,710,3,US>IL>675
11,12,6fa993bd0e0157,892701,718,1,US>TX>612
12,13,7355615832b3af,1778533,739,1,US>AZ>753
13,14,daef797fc210a2,1759953,798,3,US>NC>560
14,15,24c64dc30891c0,1777136,1000,2,GB
15,16,30c0ad12b36375,1727882,1033,1,US>FL>561
16,17,c80c06d718ba65,1667725,1044,2,US>MI>540
17,18,eb58e66b4f6bb0,429183,1175,2,US>OR>820
18,19,c419799a427c72,1155107,1202,3,US>HI>744
19,20,650e3b5699738b,1642724,1282,2,US>MI>505
20,21,95866cc26c177b,1771519,1394,2,US>NC>560
21,22,a32f03f4fdcf17,1748533,1716,2,US>NY>501
22,23,c8cefb08bef5f2,1715559,1845,2,AU>05
23,24,7f330bf68a4b41,1789836,1890,2,US>CA
24,25,983eb92a5ae4df,807380,1961,2,IN>16
25,26,5e8bf82689d3a9,1755529,2094,2,US>MI
26,27,75df5a72fe6aae,1760776,2365,2,US>CA>825
27,28,679607f26bf5c5,778157,2421,2,US>NY>501
28,29,bd28314430fb9b,9659,2433,2,US>IL>602
29,30,53ca43b326638b,1773952,2550,2,US>NJ>501
...,...,...,...,...,...,...
23120096,23120097,17590031105d03,2863100,1295998039,3,US>WA>819
23120097,23120098,7ab35b9e3ded8a,1322324,1295998048,2,US
23120098,23120099,254e8587b4c5ce,2848950,1295998082,2,US>NY>501
23120099,23120100,d8929c5750edf4,2990347,1295998125,2,US>CA>807
23120100,23120101,69a57755a0f04c,1288204,1295998137,2,US>UT>770
23120101,23120102,723f7602dc32e6,2957194,1295998223,1,US>MO>609
23120102,23120103,a91dc6bb0993c1,1576316,1295998239,1,US>TX>635
23120103,23120104,6124d425d25931,2928185,1295998254,3,US>CA>803
23120104,23120105,c2a5ca6a6b3328,2600498,1295998301,2,US>AZ>753
23120105,23120106,be0ca13b906fd4,2988490,1295998352,2,US>NY>501
23120106,23120107,1377bbaa4d91f6,504862,1295998358,2,US>CA>800
23120107,23120108,8483f4d525ab98,2979768,1295998694,1,US>NJ>501
23120108,23120109,d4eb72c90fcb1f,2934234,1295998772,2,US>NY>501
23120109,23120110,33d82a6633899a,2858368,1295998927,1,US>CA>803
23120110,23120111,edce64b6affe65,2528880,1295998950,2,US>IL>602
23120111,23120112,ded60fbfd1307d,775964,1295998987,1,US>ND>724
23120112,23120113,d51bd0fb9ad814,2866152,1295999006,2,US
23120113,23120114,4ddf04b680eca7,2992327,1295999180,1,TW>03
23120114,23120115,17c8ea006240f5,2983157,1295999298,2,US>FL>539
23120115,23120116,4fd63df99cc873,1318460,1295999344,2,DE>06
23120116,23120117,656cedaf95c5d0,2985645,1295999360,1,US>TX>618
23120117,23120118,f9e31a6bab2578,310779,1295999547,2,US>NY>538
23120118,23120119,31a19347301c57,1788295,1295999563,1,US>TX>600
23120119,23120120,ca33f12ef839dd,2306525,1295999567,1,US>IL>609
23120120,23120121,176f586048741e,1347238,1295999569,2,CA>AB
23120121,23120122,3b42aaa4aa8993,1827718,1295999574,1,US>FL>571
23120122,23120123,7efccdc2d58fd1,2984543,1295999591,2,US>TX>623
23120123,23120124,11f9ac8cee26f2,751048,1295999657,2,US>GA>524
23120124,23120125,6bbdc5756789cc,744496,1295999771,2,US>MI>505
23120125,23120126,b545c100626cba,2357447,1295999805,2,US>SD>764

In [16]:
df1 = pd.DataFrame({'a': [1, 2], 'b':[4,5]})
df2 = pd.DataFrame({'a': [9,4], 'b':[9,5]})
df1.append(df2)

   a  b
0  1  4
1  2  5
0  9  9
1  4  5

In [26]:
m[m.clicked.isnull()]

Empty DataFrame
Columns: [display_id, ad_id, clicked, uuid, document_id, timestamp, platform, geo_location]
Index: []

In [10]:
m = pd.merge(train, events, on='display_id')

In [12]:
m.groupby('platform').clicked.mean()

platform
1     0.174638
2     0.217605
3     0.180366
1     0.174819
2     0.218074
3     0.179194
\N    0.166667
Name: clicked, dtype: float64

In [21]:
# test 16874594
# train   
m[]

          display_id   ad_id  clicked
0                  1   42337        0
1                  1  139684        0
2                  1  144739        1
3                  1  156824        0
4                  1  279295        0
5                  1  296965        0
6                  2  125211        0
7                  2  156535        0
8                  2  169564        0
9                  2  308455        1
10                 3   71547        0
11                 3   95814        0
12                 3  152141        0
13                 3  183846        0
14                 3  228657        1
15                 3  250082        0
16                 4  149930        0
17                 4  153623        1
18                 4  184709        0
19                 4  186849        0
20                 4  233730        0
21                 5   54606        0
22                 5  162868        0
23                 5  184548        0
24                 5  282674        0
25                 5  326514        1
26                 6   85397        0
27                 6  160754        0
28                 6  173388        0
29                 6  175234        1
...              ...     ...      ...
87141701    16874588   23690        0
87141702    16874588  174903        0
87141703    16874588  468733        1
87141704    16874588  526478        0
87141705    16874589    3314        0
87141706    16874589  187175        0
87141707    16874589  188284        1
87141708    16874589  226819        0
87141709    16874589  243297        0
87141710    16874589  394670        0
87141711    16874590   35805        0
87141712    16874590   80235        0
87141713    16874590  132287        0
87141714    16874590  142604        1
87141715    16874590  142780        0
87141716    16874590  142816        0
87141717    16874591   36108        0
87141718    16874591  127047        1
87141719    16874591  145601        0
87141720    16874591  285839        0
87141721    16874591  397506        0
87141722    16874591  483448        0
87141723    16874592   82851        0
87141724    16874592  153244        1
87141725    16874592  167294        0
87141726    16874592  186600        0
87141727    16874593  151498        1
87141728    16874593  282350        0
87141729    16874593  521828        0
87141730    16874593  522693        0

[87141731 rows x 3 columns]